### PR TITLE
User can delete a favorite from a playlist

### LINKED ISSUE #58: User can delete a favorite from a playlist
A user can send a `DELETE /api/v1/playlists/:id/favorites/:id` request and the specific favorite by `:id` is removed from the playlist with `:id`.

Example Request: ` DELETE /api/v1/playlists/1/favorites/1`

Example Response: `status: 204`

Sad Path:
`404 {error: "No such <resource> found. No deletion made."}`
- If the playlist cannot be found, return `status: 404; body: {error: "No such playlist found. No deletion made."}`
- If the favorite cannot be found, return `status: 404; body: {error: "No such favorite found. No deletion made."}``

Testing:
- [ ] Test happy path response
- [ ] Test happy path favoritePlaylist joins resource is deleted. Both playlist and favorite still exist in their respective resource tables
- [ ] Test 404 responses
- [ ] Catch 500

- [ ] Documentation in README

### PR DESCRIPTION
**Pull request by rhantak**
- Add routing for `/playlists/:id/favorites` endpoints
- Add DELETE action for `/api/v1/playlists/favorites/:playlist_id/favorites/:favorite_id` to allow a user to remove a favorite from a playlist

Closes #58

### CODE REVIEW

File: db/migrations/20200211143227_addPlaylistFavorites.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 
 exports.up = function(knex) {
   return Promise.all([
-    knex.schema.createTable('playlistFavorites', function(table) {
+    knex.schema.createTable('playlist_favorites', function(table) {
```
Comment (ap2322) [inline db/migrations/20200211143227_addPlaylistFavorites.js]: Thanks for troubleshooting the snake vs camelCase on database/knex issue with this

File: routes/api/v1/playlists.js [hunk 2]
```diff
@@ -111,4 +112,9 @@ router.delete('/:id', (request, response) => {
     })
 })
 
+router.use('/:playlist_id/favorites', function(request, response, next) {
+  request.playlist_id = request.params.playlist_id;
+  next()
+}, favorites);
+
```
Comment (ap2322) [inline routes/api/v1/playlists.js]: I think a future refactor could look into the merge params feature, but for now this works, so yay!

File: routes/api/v1/playlists/favorites.js [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+var router = express.Router();
+
+const environment = process.env.NODE_ENV || 'development';
+const configuration = require('../../../../knexfile')[environment];
+const database = require('knex')(configuration);
+const Favorite = require("../../../../lib/models/favorite")
+
+router.delete('/:favorite_id', (request, response) => {
+  let playlistId = request.playlist_id
+  let favoriteId = request.params.favorite_id
```
Comment (ap2322) [inline routes/api/v1/playlists/favorites.js]: Thank you for figuring this out!

File: routes/api/v1/playlists/favorites.js [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+      } else {
+        database('playlists').where({id: playlistId}).select()
+          .then((playlists) => playlists.length === 1)
+          .then(playlistExists => {
+            if(playlistExists){
+            response.status(404).send({"error": "No such favorite found. No deletion made."})
+          } else {
+            response.status(404).send({"error": "No such playlist found. No deletion made."})
+          }
+        })}
```
Comment (ap2322) [inline routes/api/v1/playlists/favorites.js]: Really like this error handling
